// <auto-generated />
namespace DoAn_LapTrinhWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DoAn_LapTrinhWeb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DoAn_LapTrinhWeb));
        
        string IMigrationMetadata.Id
        {
            get { return "202303241359316_DoAn_LapTrinhWeb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
